# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Infrastructure for private-notes project

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        # Make table name accessible as environment variable from function code during execution
        SAMPLE_TABLE: !Ref SampleTable

Parameters:
  EnvironmentParameter:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: dev, prod

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Api gateway resource
  PrivateNotesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'PrivateNotes-Api-${EnvironmentParameter}'
      StageName: !Ref EnvironmentParameter
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*' # allows for logging on any resource
          HttpMethod: '*' # allows for logging on any method
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./api/openapi.yaml
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for default api key
          UsagePlanName: !Sub 'private-notes-${EnvironmentParameter}-api-usage-plan'

      Cors:
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"
        AllowOrigin: "'*'"
        AllowHeaders: "'X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"

  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  ListCollections:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list-collections.listCollections
      FunctionName: !Sub 'private-notes-${EnvironmentParameter}-ListCollections'
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/handlers/list-collections.ts

  CreateCollection:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create-collection.createCollection
      FunctionName: !Sub 'private-notes-${EnvironmentParameter}-CreateCollection'
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/handlers/create-collection.ts

  UpdateCollection:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update-collection.updateCollection
      FunctionName: !Sub 'private-notes-${EnvironmentParameter}-UpdateCollection'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/handlers/update-collection.ts

  GetCollection:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-collection.getCollection
      FunctionName: !Sub 'private-notes-${EnvironmentParameter}-GetCollection'
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/handlers/get-collection.ts

  DeleteCollection:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete-collection.deleteCollection
      FunctionName: !Sub 'private-notes-${EnvironmentParameter}-DeleteCollection'
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Sourcemap: true
        EntryPoints:
          - src/handlers/delete-collection.ts

  # Simple syntax to create a DynamoDB table with a single attribute primary key, more in
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      Path: !Sub '/private-notes/${EnvironmentParameter}/serviceRoles/'
      RoleName: !Sub 'private-notes-${EnvironmentParameter}-api-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Policies:
        - PolicyName: !Sub 'private-notes-${EnvironmentParameter}-api-execution-role-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub ${ListCollections.Arn}
                  - !Sub ${CreateCollection.Arn}
                  - !Sub ${UpdateCollection.Arn}
                  - !Sub ${GetCollection.Arn}
                  - !Sub ${DeleteCollection.Arn}

  Account:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !Sub ${ApiRole.Arn}

Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${PrivateNotesApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentParameter}/'
