openapi: 3.0.3

info:
  title: Private Notes API - OpenAPI 3.0
  description: |-
    This is an OpenAPI definition for private-notes project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params:
    validateRequestBody: true
    validateRequestParameters: true
  body:
    validateRequestBody: true
    validateRequestParameters: false

x-amazon-apigateway-api-key-source: HEADER

servers:
  - url: http://localhost:3000
    description: 'Local server'

paths:
  /collections:
    get:
      tags:
        - collection
      operationId: listCollections
      summary: List all collections
      description: Lists all available collections with minimal data set
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListCollections.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 15000
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        type: 'aws_proxy'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collection'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '405':
          $ref: '#/components/responses/MethodNotAllowedError'
        '500':
          $ref: '#/components/responses/GeneralError'
      security:
        - api_key: []

    post:
      tags:
        - collection
      operationId: createCollection
      summary: Create a new collection
      description: Create a new empty collection
      x-amazon-apigateway-request-validator: body
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateCollection.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 15000
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        type: 'aws_proxy'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: My New Collection
              required:
                - name
        required: true
      responses:
        '200':
          $ref: '#/components/responses/CollectionResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '405':
          $ref: '#/components/responses/MethodNotAllowedError'
        '500':
          $ref: '#/components/responses/GeneralError'
      security:
        - api_key: []

    put:
      tags:
        - collection
      operationId: updateCollection
      summary: Update an existing collection
      x-amazon-apigateway-request-validator: body
      requestBody:
        description: The collection object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Collection'
        required: true
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateCollection.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 15000
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        type: 'aws_proxy'
      responses:
        '200':
          $ref: '#/components/responses/CollectionResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '405':
          $ref: '#/components/responses/MethodNotAllowedError'
        '500':
          $ref: '#/components/responses/GeneralError'
      security:
        - api_key: []

  /collections/{collectionId}:
    get:
      tags:
        - collection
      operationId: getCollection
      summary: Get a collection
      description: Get a single collection with full data by it's id
      x-amazon-apigateway-request-validator: params
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetCollection.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 15000
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        type: 'aws_proxy'
      parameters:
        - name: collectionId
          in: path
          description: ID of the collection
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'
        '400':
          $ref: '#/components/responses/ValidationError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '405':
          $ref: '#/components/responses/MethodNotAllowedError'
        '500':
          $ref: '#/components/responses/GeneralError'
      security:
        - api_key: []

    delete:
      tags:
        - collection
      summary: Delete collection
      description: Delete a collection by collectionId
      operationId: deleteCollection
      x-amazon-apigateway-request-validator: params
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteCollection.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 15000
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        type: 'aws_proxy'
      parameters:
        - name: collectionId
          in: path
          description: ID of the collection that needs to be deleted
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/DeleteSuccessResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '405':
          $ref: '#/components/responses/MethodNotAllowedError'
        '500':
          $ref: '#/components/responses/GeneralError'
      security:
        - api_key: []

  /collections/{collectionId}/notes:
    post:
      tags:
        - note
      operationId: createNote
      summary: Create a new note
      x-amazon-apigateway-request-validator: all
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateNote.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 15000
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        type: 'aws_proxy'
      parameters:
        - name: collectionId
          in: path
          description: ID of the collection the note that needs to be deleted is in
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - collectionId
              properties:
                collectionId:
                  type: string
                  format: uuid
                title:
                  type: string
                  example: Reminder
                content:
                  type: string
                  example: Do stuff!
        required: true
      responses:
        '200':
          $ref: '#/components/responses/NoteResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '405':
          $ref: '#/components/responses/MethodNotAllowedError'
        '500':
          $ref: '#/components/responses/GeneralError'
      security:
        - api_key: []

  /collections/{collectionId}/notes/{noteId}:
    put:
      tags:
        - note
      operationId: updateNote
      summary: Update an existing note
      x-amazon-apigateway-request-validator: all
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateNote.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 15000
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        type: 'aws_proxy'
      parameters:
        - name: collectionId
          in: path
          description: ID of the collection the note that needs to be deleted is in
          required: true
          schema:
            type: string
            format: uuid
        - name: noteId
          in: path
          description: ID of the note that needs to be deleted
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated note params
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/NoteResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '405':
          $ref: '#/components/responses/MethodNotAllowedError'
        '500':
          $ref: '#/components/responses/GeneralError'
      security:
        - api_key: []

    delete:
      tags:
        - note
      operationId: deleteNote
      summary: Delete note
      x-amazon-apigateway-request-validator: params
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteNote.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 15000
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        type: 'aws_proxy'
      parameters:
        - name: collectionId
          in: path
          description: ID of the collection the note that needs to be deleted is in
          required: true
          schema:
            type: string
            format: uuid
        - name: noteId
          in: path
          description: ID of the note that needs to be deleted
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/DeleteSuccessResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '405':
          $ref: '#/components/responses/MethodNotAllowedError'
        '500':
          $ref: '#/components/responses/GeneralError'
      security:
        - api_key: []

components:
  schemas:
    StoredEntity:
      type: object
      properties:
        createdAt:
          type: number
          format: int64
        updatedAt:
          type: number
          format: int64
        removedAt:
          type: number
          format: int64

    Collection:
      allOf:
        - type: object
          required:
            - collectionId
            - name
          properties:
            collectionId:
              type: string
              format: uuid
            name:
              type: string
            notes:
              type: array
              items:
                $ref: '#/components/schemas/Note'
        - $ref: '#/components/schemas/StoredEntity'
    Note:
      allOf:
        - type: object
          required:
            - collectionId
            - noteId
            - title
            - content
            - tags
          properties:
            collectionId:
              type: string
              format: uuid
            noteId:
              type: string
              format: uuid
            title:
              type: string
            content:
              type: string
            tags:
              type: array
              items:
                type: string
        - $ref: '#/components/schemas/StoredEntity'

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 1000
        message:
          type: string
          example: Error happened while updating a collection
      required:
        - message
  responses:
    CollectionResponse:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Collection'
    NoteResponse:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Note'
    DeleteSuccessResponse:
      description: Successful delete
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
                format: uuid
    GeneralError:
      description: Error returned in case of Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ValidationError:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    MethodNotAllowedError:
      description: Method not allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundError:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ForbiddenError:
      description: Forbidden

  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-api-key
      x-amazon-apigateway-api-key-source: HEADER
